### PR TITLE
Changed JaxRsHalBuilderSupport to be non-generic and fixed tests.

### PR DESCRIPTION
**Pull request by mg-2014**
Changed JaxRsHalBuilderSupport to be non-generic and fixed tests.

Regards,
Markus

### CODE REVIEW

**Comment by mg-2014** [comment]
Changed version of JAX-RS API to 2.0 because of:

>Please note that JAX-RS 2.1 is not final yet. JAX-RS 2.1 might change, there is no backwards compatibility requirement to keep among 2.26-bXX builds. Use at your own risk.
(https://jersey.github.io/download.html)

**Comment by mg-2014** [comment]
The Travis CI build fails because `halbuilder-jaxrs` seems to use `halbuilder-core` 5.0.1 instead of 5.1.1-SNAPSHOT and thus doesn't find `Support.HAL_JSON`. I left the version bracket notation for the `halbuilder-core` version untouched. Should work as soon as 5.1.1 is released.

**Comment by talios** [comment]
Cheers - 5.1.1 of core has been released and I've just merged this, and bumped the versions of core and itself to 5.1.1 - shall I go ahead and release this?

**Comment by mg-2014** [comment]
Excellent. I see you have already released it. Thanks.

**Pull request merged**
